name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm toolchain
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: "0.2.108"

      - name: Run tests
        run: |
          cargo test
          cargo test --target wasm32-unknown-unknown
        env:
          RUST_BACKTRACE: 1

      - name: Run build
        run: |
          cargo build
          cargo build --target wasm32-unknown-unknown
        env:
          RUST_BACKTRACE: 1
